 language: python
 python:
     - "3.7"

 sudo: false
 cache:
     directories:
         - "~/.platformio"

 install:
     - pip install -U platformio
     - platformio update
     - platformio lib install ArduinoJson
     - platformio lib install WiFiManager

 script:
     - platformio run
